### PR TITLE
Add security.txt.

### PR DESCRIPTION
**Pull request by DailyDreaming**

### CODE REVIEW

**Comment by mweiden** [comment]
@DailyDreaming why not simply add this to the `README.md`?

**Comment by DailyDreaming** [comment]
@mweiden It's the convention typically used.  Some helpful info here: https://ankitvijay.net/2018/02/04/add-security-txt-to-your-web-app/

**Comment by kislyuk** [comment]
Adding this file to the repository does not make it show up in `/.well-known/security.txt`. We should have a general purpose "Reporting bugs" section in the readme, with a security note in it referring to a page on the data portal. We should also file a task for each team to change their service router to have the same blurb show up in `https://SERVICE.data.humancellatlas.org/.well-known/security.txt`

**Comment by kislyuk** [comment]
I am going to close this without merging for now. When the HCA DCP landing page gets a "Security contact" section, I am going to include a "Security issues" section in the Query Service repo readme and documentation, linking to that section.

I recommend that a similar pattern be followed elsewhere in the DCP. I don't think the "security.txt" file at the root of each repo will be seen by those who need it, so I don't recommend that it be used.

**Pull request closed without merging**
